---                                                                                            
- name: Configure Hypervisor
  hosts: localhost 
  gather_facts: true
  become: yes
  roles: 
    - ansible-role-generic-setup
    - ansible-role-install-kvm
    - ansible-role-install-docker
    - ansible-role-install-pip
    - ansible-role-deploy-jenkins
